services:
    main_app:
        build:
            context: ./
            dockerfile: Dockerfile
        ports:
            - "8080:8080"
        depends_on:
            memcached:
                condition: service_started
            mariadb:
                condition: service_healthy

    memcached:
        build:
            context: ./
            dockerfile: Dockerfile.memcached
    
    mariadb:
        build:
            context: ./
            dockerfile: Dockerfile.mariadb
        healthcheck:
            test: "ss -lt4n | grep '3306'"
            interval: 1m30s
            timeout: 30s
            retries: 5
            start_period: 30s
        environment:
            - MARIADB_DATABASE=test_db